export const SET_USERS_LIST = 'SET_USERS_LIST';
export const ADD_USER = 'ADD_USER';
export const SET_AUTHORIZED_USER = 'SET_AUTHORIZED_USER';
export const RESET_AUTHORIZED_USER = 'RESET_AUTHORIZED_USER';

export default {
    SET_USERS_LIST,
    ADD_USER,
    SET_AUTHORIZED_USER,
    RESET_AUTHORIZED_USER
};
